import Head from 'next/head'

import Image from 'next/image'
import styles from '../styles/Home.module.css'
import LandingPage from './LandingPage/LandingPage'

export default function Home(props) {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
      </Head>

      <main>
      <LandingPage data={props.data}/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  debugger
  
  const res = await fetch('https://api.bigcommerce.com/stores/xcevhqdz/v3/catalog/products', {
    method: 'get',
    headers: { 
      'X-Auth-Token': 'q3jt8f7mc249hr0a7dakrp6eiv5bztv', 
      'X-Auth-Client':'sig2x6d2vjsyw8w1gj63rprgn8ye51k',
      'Accept': 'application/json',
      'Access-Control-Allow-Origin': 'http://localhost:3000',
      "Access-Control-Allow-Headers": "x-requested-with, x-requested-by" 
    }
  })
  const data = await res.json()
console.log(data.data+"jwbwiwhihdiwhdwihdwidhiwhdwidhiwhdiwhdiwhdiwhidwdwi")
  
  //const data = await axios(config)
  
  return {
    props:{
      data
    }
  }
}